@baseUrl = http://localhost:3000

###Ajout d'un site avec un mot de passe OK
POST {{baseUrl}}/sites/addSite 
Content-Type: application/json

{
"userId":"5",
"urlSite":"test01",
"siteName":"testSite1",
"userNameSite":"Useraname1",
"passwordSite":"patate05"
}


### DELETE a site and his password OK
DELETE {{baseUrl}}/sites/deleteSite
Content-Type: application/json

{
    "userId": "2",
    "id": "2"
}



### UPDATE elements for a site OK
PATCH {{baseUrl}}/sites/updateSite 
Content-Type: application/json

{
    "userId": "2",
    "login": "kilian",
    "url":"https://localhost:4000",
    "site":"facebook",
    "id":"21",
    "password":"patate07"
    
}
###ORDER BY NAME SITE OK
POST {{baseUrl}}/sites/orderBySiteName
Content-Type: application/json

{
    "username" : "azerty"
}

###ORDER BY DATE OK
POST {{baseUrl}}/sites/orderByDate
Content-Type: application/json

{
    "username" : "azerty"
}

### GET Site By Id OK
POST {{baseUrl}}/sites/getSiteById
Content-Type: application/json

{   
    "userId" : "2",
    "siteId" : "1"
    
}