@baseUrl = http://localhost:3000

###Ajout d'un site avec un mot de passe 
POST {{baseUrl}}/sites/addSite
Content-Type: application/json

{
"userId":"2",
"urlSite":"test01",
"siteName":"testSite1",
"userNameSite":"Useraname1",
"passwordSite":"patate05"
}


### DELETE a site and his password
DELETE {{baseUrl}}/sites/deleteSite
Content-Type: application/json

{
    "userId": "2",
    "id": "20"
}



### UPDATE elements for a site
PATCH {{baseUrl}}/sites/updateSite
Content-Type: application/json

{
    "userId": "2",
    "login": "kilian",
    "url":"https://localhost:4000",
    "site":"facebook",
    "id":"21",
    "password":"patate07"
    
}